# Generated by Django 6.0.5 on 2026-09-27 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='profile_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='doctors/'),
        ),
    ]
