# Generated by Django 6.0.5 on 2026-09-21 18:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='Unique URL identifier automatically generated from title.', max_length=220, unique=True)),
                ('short_description', models.CharField(help_text='Brief summary shown on update cards.', max_length=255)),
                ('content', models.TextField(help_text='Full update / announcement content.')),
                ('image', models.ImageField(blank=True, help_text='Optional header / announcement image.', null=True, upload_to='health_updates/')),
                ('category', models.CharField(choices=[('General Health', 'General Health'), ('Health Awareness', 'Health Awareness'), ('Nutrition', 'Nutrition'), ('Wellness', 'Wellness'), ('Preventive Care', 'Preventive Care'), ('MediNest Updates', 'MediNest Updates')], default='General Health', max_length=50)),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this update is visible to the public.')),
                ('is_featured', models.BooleanField(default=False, help_text='Designates whether this update is highlighted on the homepage.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Health Update / Announcement',
                'verbose_name_plural': 'Health Updates & Announcements',
                'ordering': ['-is_featured', '-published_date', '-created_at'],
            },
        ),
    ]
