# Generated by Django 6.0.5 on 2026-09-21 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_healthupdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(help_text='Gallery photo / image file.', upload_to='gallery/')),
                ('description', models.TextField(blank=True, help_text='Optional caption or details for the photo.')),
                ('category', models.CharField(choices=[('Healthcare', 'Healthcare'), ('Wellness', 'Wellness'), ('Doctors', 'Doctors'), ('Awareness', 'Awareness'), ('Events', 'Events'), ('MediNest', 'MediNest')], default='Healthcare', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this media item is visible in the public gallery.')),
                ('is_featured', models.BooleanField(default=False, help_text='Designates whether this media item is highlighted on the homepage.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Gallery Item',
                'verbose_name_plural': 'Gallery Items',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
    ]
