# Generated by Django 6.0.5 on 2026-09-27 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryitem',
            name='image',
            field=models.ImageField(help_text='Gallery photo / image file.', max_length=255, upload_to='gallery/'),
        ),
        migrations.AlterField(
            model_name='healthupdate',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional header / announcement image.', max_length=255, null=True, upload_to='health_updates/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='services/'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='profile_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='testimonials/'),
        ),
    ]
